server:
  http:
    addr: 0.0.0.0:30001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:30002
    timeout: 1s
data:
  database:
    source: postgres://root:msdnmm@103.71.69.244:5432/bank?sslmode=disable&pool_max_conns=10
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
